using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;
using XInputDotNetPure;
public class PauseMenuHandler : MonoBehaviour
{

    public GameObject Container;
    InputManager input;
    bool isPaused;
    bool pause;
    Player player;
    void Awake()
    {
        player = GameObject.FindGameObjectWithTag("Player").GetComponentInChildren<Player>();
        input = GameObject.Find("InputManager").GetComponent<InputManager>();
        input.pauseMenuHandler = this;

        Container.SetActive(false);
    }

    void Update()
    {
        if (player.CurrentHealth < 0)
        {
            Debug.Log("Dead");
            Container.SetActive(true);
            isPaused = Container.activeSelf;
        }
    }

    public void HandleInput(GamePadState state, GamePadState prevState)
    {
        if (prevState.Buttons.Start == ButtonState.Released && state.Buttons.Start == ButtonState.Pressed)
        {
            if (!pause)
            {
                pause = true;
                Container.SetActive(!Container.activeSelf);
                isPaused = Container.activeSelf;
                Time.timeScale = 0;
              
            }
            else
            {
                ResumeGame();
            }

          
        }
    }

    public void ChangeScene(string name)
    {
        SceneManager.LoadScene(name);
    }
    public void ResumeGame()
    {
        pause = false;
        Container.SetActive(!gameObject.activeSelf);
        isPaused = Container.activeSelf;
        Time.timeScale = 1;
    }
    public void QuitGame()
    {
        Application.Quit();
    }
}
